language: cpp

sudo: false
addons:
    apt:
        packages:
            - cmake
            - g++-4.8
compiler: gcc
before_install: 
    - export CXX="g++-4.8"
script: 
    - mkdir build && cd build
    - cmake .. && make
