language: cpp

sudo: false
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - cmake
            - gcc-4.8
            - g++-4.8
compiler: gcc
before_install: 
    - export CXX="g++-4.8"
script: 
    - mkdir build && cd build
    - cmake .. && make
